name: Set Build Metadata

on:
  workflow_call:
    outputs:
      build_timestamp:
        description: "UTC timestamp of the build"
        value: ${{ jobs.set-metadata.outputs.build_timestamp }}
      short_sha:
        description: "Short commit SHA"
        value: ${{ jobs.set-metadata.outputs.short_sha }}
      branch_name:
        description: "Branch name"
        value: ${{ jobs.set-metadata.outputs.branch_name }}

jobs:
  set-metadata:
    runs-on: ubuntu-latest
    outputs:
      build_timestamp: ${{ steps.export.outputs.build_timestamp }}
      short_sha: ${{ steps.export.outputs.short_sha }}
      branch_name: ${{ steps.export.outputs.branch_name }}

    steps:
      - name: Export metadata to env
        id: export
        run: |
          echo "build_timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "branch_name=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
